Fix JSX syntax errors: add missing closing div tags
Error: Unexpected closing fragment tag does not match opening div tag

Fixed by adding missing </div> before </> in all three custom modals:

Structure should be:
<>
  <div>{/* backdrop */}</div>
  <div>
    {/* modal content */}
  </div>   Was missing this!
</>

Added missing closing divs to:
- Version History modal (3 locations)
- Insert Image modal (3 locations)
- Insert YouTube modal (3 locations)

Files fixed:
- app/components/NotionTiptapEditor.jsx
- app/components/AdvancedRTE.jsx